autoload -U bashcompinit
bashcompinit
setopt incappendhistory autocd extendedglob
unsetopt beep nomatch notify
setopt prompt_subst
setopt NO_HUP

# Disable c-s hanging of terminal
stty -ixon

# Bindings
bindkey '^p' up-history
bindkey '^n' down-history
bindkey '^?' backward-delete-char
bindkey '^d' delete-char
bindkey '^[d' delete-word
bindkey '^y' yank
bindkey '^w' backward-kill-word
bindkey '^b' backward-char
bindkey '^[b' backward-word
bindkey '^f' forward-char
bindkey '^[f' forward-word
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

# Visual mode fixes
export KEYTIMEOUT=1

#Configurations
conf() {
  cd $HOME/workspace/nixfiles
  f=$(fd -t f . | fzf)
  sha1=$(sha1sum $f | awk '{print $1}')
  nvim $f
  newsha1=$(sha1sum $f | awk '{print $1}')
  test $sha1 != $newsha1 && home-manager switch
  cd - 1>/dev/null
}

# forgit
if [ ! -f $ZDOTDIR/forgit/forgit.plugin.zsh ]; then
  git clone https://github.com/wfxr/forgit $ZDOTDIR/forgit/
fi
source $ZDOTDIR/forgit/forgit.plugin.zsh

# Vim mode improvements
export KEYTIMEOUT=10
bindkey -M viins 'jk' vi-cmd-mode


# pipenv
export PIPENV_VENV_IN_PROJECT=1

function preexec() {
    _tmux_update_env
    _update_agents
}

export DO_NOT_TRACK=1

#pyright
export PYRIGHT_PYTHON_IGNORE_WARNINGS=1

# Lazy-loading completion
if [ $commands[bw] ]; then
  bw() {
    unfunction "$0"
    eval "$(bw completion --shell zsh); compdef _bw bw;"
    $0 "$@"
  }
fi
if [ $commands[klog] ]; then
  klog() {
    unfunction "$0"
    source <(klog completion -c zsh)
    $0 "$@"
  }
fi
if [ $commands[pipenv] ]; then
  pipenv() {
    unfunction "$0"
    eval "$(_PIPENV_COMPLETE=zsh_source pipenv)"
    $0 "$@"
  }
fi
if [ $commands[pip] ]; then
  pip() {
    unfunction "$0"
    eval "$(pip completion --zsh)"
    $0 "$@"
  }
fi

if [ $commands[jj] ]; then
  jj() {
    unfunction "$0"
    source <(COMPLETE=zsh jj)
    $0 "$@"
  }
fi


if [ $commands[uv] ]; then
  uv() {
    unfunction "$0"
    eval "$(uv --generate-shell-completion zsh)"
    $0 "$@"
  }
fi

eval "$(capbak completion)"
eval "$(mimir completion)"
eval "$(search completion)"

if [ $commands[kubectl] ]; then
  kubectl() {
    unfunction "$0"
    eval "$(kubectl completion zsh)"
    $0 "$@"
  }
fi

#----Machine-specific----
test -f $ZDOTDIR/machine_specific && source $ZDOTDIR/machine_specific
