# Disable c-s hanging of terminal
stty -ixon

# Bindings
bindkey '^p' up-history
bindkey '^n' down-history
bindkey '^?' backward-delete-char
bindkey '^d' delete-char
bindkey '^[d' delete-word
bindkey '^y' yank
bindkey '^w' backward-kill-word
bindkey '^b' backward-char
bindkey '^[b' backward-word
bindkey '^f' forward-char
bindkey '^[f' forward-word
bindkey '^a' beginning-of-line
bindkey '^e' end-of-line

# Vim mode improvements
KEYTIMEOUT=10
bindkey -M viins 'jk' vi-cmd-mode

function precmd() {
  _tmux_update_env
  _update_agents
}

#----Machine-specific----
test -f "$ZDOTDIR/machine_specific" && source "$ZDOTDIR/machine_specific"
